# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  
  config.ssh.insert_key = false
   
  # Server   
  config.vm.define "server" do |server|
    server.vm.box = "jhveras/freeipa-server-lab"
    server.vm.box_version = "0.0.3"
    
    server.vm.network "private_network", ip: "192.168.99.230"
    
    server.vm.provider "virtualbox" do |vb|  
      vb.memory = "2560"
    end
    
    server.vm.provision "shell", inline: <<-SHELL
      hostnamectl set-hostname master.lab.example.com
      nmcli connection delete "enp0s8"
      nmcli connection add type ethernet ifname enp0s8 con-name enp0s8 ipv4.addresses 192.168.99.230/24 ipv4.dns 192.168.99.230 ipv4.dns-search lab.example.com ipv4.method manual connection.autoconnect yes
      nmcli connection up enp0s8
    SHELL
  end  
  
  # Client 01
  config.vm.define "node01" do |node01|
    node01.vm.box = "jhveras/freeipa-client01-lab"
    node01.vm.box_version = "0.0.1"
    
    node01.vm.network "private_network", ip: "192.168.99.235"
    
    node01.vm.provider "virtualbox" do |vb|  
      vb.memory = "1024"
    end
    
    # Configure networking
    node01.vm.provision "shell", inline: <<-SHELL
      hostnamectl set-hostname node01.lab.example.com
      nmcli connection delete "System enp0s8"
      nmcli connection add type ethernet ifname enp0s8 con-name enp0s8 ipv4.addresses 192.168.99.235/24 ipv4.dns 192.168.99.230 ipv4.dns-search lab.example.com ipv4.method manual connection.autoconnect yes
      nmcli connection up enp0s8
    SHELL
  end
  
  # Client 02
  config.vm.define "node02" do |node02|
    node02.vm.box = "jhveras/freeipa-client02-lab"
    node02.vm.box_version = "0.0.1"
    
    node02.vm.network "private_network", ip: "192.168.99.236"
    
    node02.vm.provider "virtualbox" do |vb|  
      vb.memory = "1024"
    end
    
    # Configure networking
    node02.vm.provision "shell", inline: <<-SHELL
      hostnamectl set-hostname node02.lab.example.com
      nmcli connection delete "System enp0s8"
      nmcli connection add type ethernet ifname enp0s8 con-name enp0s8 ipv4.addresses 192.168.99.236/24 ipv4.dns 192.168.99.230 ipv4.dns-search lab.example.com ipv4.method manual connection.autoconnect yes
      nmcli connection up enp0s8
    SHELL
  end
  
end
